return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    main = "nvim-treesitter.configs",
    opts = {
        ensure_installed = {
            "bash",
            "cmake",
            "css",
            "go",
            "html",
            "javascript",
            "json",
            "lua",
            "python",
            "toml",
            "vim",
            "yaml",
            "markdown",
            "markdown_inline",
        },
        highlight = { enable = true },
        indent = { enable = true },
        autopairs = { enable = true },
    },
}
